from __future__ import annotations

from ...agent.workflow_agent import WorkflowAgent
from ...engine.loader import WorkflowLoader


class CallerProjectAgent(WorkflowAgent):
    """
    Agent for interacting with the CallerProject workflow.
    Uses the dynamically generated engine registered by @workflow.
    """

    def __init__(self, engine):
        # Load the engine class generated by the @workflow decorator
        EngineClass = WorkflowLoader.load_engine("caller_project")

        # Initialize the parent WorkflowAgent
        super().__init__(engine)
