# src/pensive/models.py

from pydantic import BaseModel

class IdeaModel(BaseModel):
    """Base class for ideas generated by strategies."""
    # Subclasses will define their own fields
    pass


class CorpusModel(BaseModel):
    """Base class for corpus items."""
    # Subclasses define fields like id, title, body, etc.
    pass


from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional, Literal
import uuid

class IdeaSummary(BaseModel):
    key: str
    idea: Optional[str] = None

class Decision(BaseModel):
    decision_id: str
    turn_id: str
    timestamp: datetime
    idea: IdeaSummary
    rationale: str
    status: Literal["accepted", "rejected", "deferred"]

    @property
    def key(self) -> str:
        return self.idea.key

    @classmethod
    def from_raw(cls, raw: dict):
        """Convert a raw decision dict into a typed Decision."""
        return cls(
            decision_id=raw["decision_id"],
            turn_id=raw["turn_id"],
            timestamp=datetime.fromisoformat(raw["timestamp"].replace("Z", "+00:00")),
            idea=IdeaSummary(**raw["idea"]),
            rationale=raw["rationale"],
            status=raw["status"],
        )
